version: '3.4'

services:
  SymptoMedit.WebApi:
    image: symptomedic-api
    build:
      context: SymptoMedic.WebApi
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 44391:44391
  
  SymptomaticApp-UI: 
    image: symptomedic-ui
    build:
      context: SymptomaticApp-UI
      dockerfile: ./dockerfile
    enviroment:
      NODE_ENV: production
    ports:
      - 4200:4200 