apiVersion: v1
kind: Namespace
metadata:
  name: symptomedic

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: symptomedic-api
  name: azure-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: symptomatic
    role: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptomatic-webapi
  labels:
    app: symptomatic
    role: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symptomatic
      role: api
  template:
    metadata:
      labels:
        app: symptomatic
        role: api
    spec:
      imagePullSecrets:
      - name: symptomatic-webapi
      containers:
      - name: api
        image: bacoordinationp3.azurecr.io/kwedwick/symptomedic-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 44391
