trigger:
  branches:
    include:
    - main
    - Develop
  paths:
    include:
    - SymptomaticApp-UI

pr:
  branches:
    include:
    - main
    - Develop
  paths:
    include:
    - SymptomaticApp-UI

variables:
  appDir: SymptomaticApp-UI
  cReg: '2107-p3-acr-P3-SymptoMedic'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: node 14
      inputs:
        versionSpec: '14.x'

    - script: npm ci
      displayName: npm install
      workingDirectory: $(appDir)

    - script: npx ng build
      displayName: ng build
      workingDirectory: $(appDir)

    - script: npx ng test --browsers ChromeHeadless --watch false --code-coverage || true
      displayName: ng test
      workingDirectory: $(appDir)

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SymptoMedic_Sonarcloud'
        organization: '210726-wvu-net-ext'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'SymptoMedic-Frontend'
        cliProjectName: 'SymptoMedic-Frontend'
        cliSources: '$(appDir)/src'
        extraProperties: |
          sonar.javascript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info
          sonar.coverage.exclusions=**/*.spec.ts
    - task: SonarCloudAnalyze@1
      displayName: sonar run analysis

    - task: SonarCloudPublish@1
      displayName: sonar publish analysis result
      inputs:
        pollingTimeoutSec: '300'

    - task: PublishBuildArtifacts@1
      inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
    
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
        artifactName: 'drop'
