apiVersion: v1
kind: Namespace
metadata:
  name: symptomedic

---
apiVersion: v1
kind: Service
metadata:
  name: symptomatic-frontend
  labels:
    app: symptomatic
    role: ui
spec:
  type: NodePort
  selector:
    app: symptomatic
    role: ui
  ports:
  - port: 80
    nodePort: 30006

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptomatic-frontend
  labels:
    app: symptomatic
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symptomatic
      role: ui
  template:
    metadata:
      labels:
        app: symptomatic
        role: ui
    spec:
      imagePullSecrets:
      - name: symptomatic-frontend
      containers:
      - name: ui
        image: symptomatic/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
