apiVersion: v1
kind: Namespace
metadata:
  name: symptomedic

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: symptomedic-ui
  name: symptomedic-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: symptomedic
    role: ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptomedic-frontend
  labels:
    app: symptomedic
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symptomedic
      role: ui
  template:
    metadata:
      labels:
        app: symptomedic
        role: ui
    spec:
      imagePullSecrets:
      - name: symptomedic-frontend
      containers:
      - name: ui
        image: bacoordinationp3.azurecr.io/kwedwick/symptomedic-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

