apiVersion: v1
kind: Namespace
metadata:
  name: symptomedic

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: symptomedic-ui
  name: azure-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: symptomatic
    role: ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptomatic-frontend
  labels:
    app: symptomatic
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symptomatic
      role: ui
  template:
    metadata:
      labels:
        app: symptomatic
        role: ui
    spec:
      imagePullSecrets:
      - name: symptomatic-frontend
      containers:
      - name: ui
        image: bacoordinationp3.azurecr.io/kwedwick/symptomatic-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
